#!/usr/bin/env bash
g=grapes-2.18
rm -rf $g $g.tar.gz
mkdir -p $g/lib/core $g/lib/services $g/config
cp -r bin $g/
cp config/train.yaml $g/config/
cp target/$g-core.jar $g/lib/core/
tar -czf $g.tar.gz $g
