name: grapes-ci

on:
  pull_request:
  push:
    branches: [ development ]
    tags: [ '*' ]

defaults:
  run:
    shell: bash

env:
  java_version: 17
  java_distribution: zulu

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
      - uses: cvmfs-contrib/github-action-cvmfs@v5
        with:
          cvmfs_repositories: 'oasis.opensciencegrid.org'
      - name: build
        run: mvn package
      - name: tar
        run: ./build-tarball
      - uses: actions/upload-artifact@v4
        with:
          name: build_${{ matrix.runner }}
          retention-days: 1
          path: grapes*.tar.gz
  
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build_ubuntu-latest
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: grapes-?.tar.gz
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

